Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),
    path('account/', include('users.urls')),

    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('captcha/', include('captcha.urls')),

]


if settings.DEBUG:

    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from . import views
from django.views.decorators.cache import cache_page

urlpatterns = [
    path('', views.main_page, name='home'),
    # path('', cache_page(30)(views.main_page), name = 'home'),
    path('news/<int:pk>/', views.full_news, name='full_news'),
    path('news_category/<int:pk>/', views.category_news_list,
         name='category_news_list'),
    path('news_author/<int:pk>/', views.author_news_list, name='author_news_list'),
    path('author_full_list/', views.author_full_list, name='author_full_list'),
    path('feedback/', views.give_feedback, name='feedback'),
    path('add_post/', views.add_post, name='add_post'),
    path('post_update/<int:pk>/', views.post_update, name='post_update'),
    path('post_delete/<int:pk>/', views.post_delete, name='post_delete'),
]

news/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from mptt.models import MPTTModel, TreeForeignKey
from django.conf import settings
from django.urls import reverse, reverse_lazy



class Post (models.Model):
    title = models.CharField(max_length=150, verbose_name='Заголовок')
    content = RichTextUploadingField(verbose_name='Текст новости')
    preview_photo = models.ImageField(
        upload_to='preview_photo/%Y/%m/%d/', verbose_name='Обложка',
        blank=True)
    date_creation = models.DateTimeField(
        auto_now_add=True, verbose_name='Дата создания')
    date_change = models.DateTimeField(
        auto_now=True, verbose_name='Дата изменения')
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        verbose_name='Автор')
    category = TreeForeignKey(
        'Category', on_delete=models.CASCADE, verbose_name='Категория')
    is_published = models.BooleanField(verbose_name='Опубликовать?',
                                       default=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('full_news', kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('post_update', kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('post_delete', kwargs={'pk': self.pk})

    class Meta:
        ordering = ["-date_creation"]
        verbose_name = 'Публикация'
        verbose_name_plural = 'Публикации'


class Category(MPTTModel):
    title = models.CharField(max_length=50, unique=True)
    parent = TreeForeignKey('self', on_delete=models.CASCADE,
                            null=True, blank=True, related_name='children')

    class MPTTMeta:
        order_insertion_by = ['title']

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('category_news_list', args=[str(self.pk)])


class Comment(MPTTModel):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments')
    parent = TreeForeignKey('self', on_delete=models.CASCADE,
                            null=True, blank=True, related_name='children')
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        verbose_name='Автор коментраия')
    comment_text = models.TextField(verbose_name='Текст коментария')
    publication_date = models.DateTimeField(
        auto_now_add=True, verbose_name='Дата создания')

    class MPTTMeta:
        order_insertion_by = ['publication_date']

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.comment_text

news/forms.py
from django import forms
from django.forms.widgets import Textarea
from captcha.fields import CaptchaField
from .models import Post, Comment
from django.forms import ModelForm
from mptt.forms import TreeNodeChoiceField


class AddPostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', 'preview_photo', 'category',
                  'is_published')


class FeedbackForm (forms.Form):
    message = forms.CharField(widget=forms.Textarea, label="Сообщение")
    captcha = CaptchaField(label='Введите текст с картинки')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment_text', 'parent')

news/views.py
from django.shortcuts import render
from .models import Post, Category, Comment
from django.core.paginator import Paginator
from django.core.mail import send_mail
from django.shortcuts import redirect
from .forms import FeedbackForm, AddPostForm, CommentForm
from django.contrib import messages
from users.models import ProfileAuthor
from django.contrib.auth.decorators import login_required, permission_required
from django.db.models import Count
from .utils import send_feedback_email
from django.db.models import Q



# Для уменьшения количества повторяющегося кода
def get_pagination(request, query):
    paginator = Paginator(query, 6)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)  # ЗАмена list_all_news
    page_numbers = paginator.get_elided_page_range()
    pg = {
        'page_obj': page_obj,
        'paginator': paginator,
        'page_numbers': page_numbers,
        'page_number': page_number,
    }
    return pg


def author_full_list(request):

    # Не работает:
    # authors = NewUser.objects.annotate(num=Count('post')).filter(is_author=True, num__gt=0).select_related('profileauthor__category','profileauthor__bio')

    return render(request, 'news/author_full_list.html')


def post_delete(request, pk):
    actual_post = Post.objects.get(pk=pk)
    actual_user = request.user
    if actual_user == actual_post.author:
        if request.method == 'POST':
            actual_post.delete()
            messages.success(request, 'Пост удален')
            return redirect('home')
        return render(request, 'news/post_delete.html', {'post': actual_post})

    else:
        messages.warning(request, 'Вы можете удалять только свои посты')
        return redirect(actual_post)


def post_update(request, pk):
    actual_post = Post.objects.get(pk=pk)
    actual_user = request.user
    if actual_user == actual_post.author:
        if request.method == "POST":
            form = AddPostForm(request.POST, request.FILES,
                               instance=actual_post)
            if form.is_valid():
                update_actual_post = form.save()
                messages.success(request, 'Пост изменен')
                return redirect(update_actual_post)
            else:
                messages.success(request, 'Ошибка валидации')
                return redirect('post_update')
        else:
            form = AddPostForm(instance=actual_post)
            return render(request, 'news/post_update.html', {'form': form})
    else:
        messages.warning(
            request, 'У вас нет прав на редaктирование этого поста')
        return redirect(actual_post)


@permission_required('news.add_post', raise_exception=True)
def add_post(request):
    if request.method == 'POST':
        form = AddPostForm(request.POST, request.FILES)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.author = request.user
            new_post.save()
            messages.success(request, 'Новость добавлена')
            return redirect(new_post)
        else:
            messages.warning(request, 'Ошибка валидации')
            return redirect('add_post')
    else:
        form = AddPostForm()
    return render(request, 'news/add_post.html', {'form': form})


def page_search(request):
    search_query = request.GET.get('search', '')
    if search_query:
        selected_news = Post.objects.select_related('category', 'author').filter(
            Q(title__icontains=search_query) |
            Q(content__icontains=search_query) |
            Q(author__full_name__icontains=search_query) |
            Q(category__title__icontains=search_query))
    else:
        selected_news = Post.objects.filter(
            is_published=True).select_related('category', 'author')

    context = {
        'selected_news': selected_news
    }
    context.update(get_pagination(request, selected_news))
    return context


def main_page(request):
    context = {}
    if request.user.is_authenticated:
        context.update(page_search(request))
        return render(request, 'base_news.html', context)
    return render(request, 'news/unauthorized_user.html')


def write_comment(request, form, selected_post):
    new_comment = form.save(commit=False)
    new_comment.user = request.user
    new_comment.post = selected_post
    new_comment.save()
    return new_comment


@login_required()
def full_news(request, pk):
    selected_post = Post.objects.get(pk=pk)
    comments = Comment.objects.filter(
        post=selected_post).select_related('post', 'user', 'parent')
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            write_comment(request, form, selected_post)
            messages.success(request, 'Коментарий добавлен!!')
            return redirect(selected_post)
        else:
            messages.warning(request, 'Ошибка валидации')
            return redirect(selected_post)
    else:
        form = CommentForm()

    context = {'selected_post': selected_post,
               'comments': comments,
               'form': form
               }
    return render(request, 'news/full_news.html', context)


@login_required()
def category_news_list(request, pk):
    posts_selected_category = Post.objects.filter(
        category=pk).select_related('category', 'author')
    selected_category = Category.objects.get(pk=pk)
    context = {
        'selected_category': selected_category,
    }
    context.update(get_pagination(request, posts_selected_category))
    return render(request, 'news/category_news_list.html', context)


@login_required()
def author_news_list(request, pk):
    posts_selected_author = Post.objects.filter(
        author=pk).select_related('category', 'author')
    context = {}
    if posts_selected_author:
        name_author = posts_selected_author.first().author
        context = {
            'name_author': name_author,
        }
        context.update(get_pagination(request, posts_selected_author))
    return render(request, 'news/author_news_list.html', context)


@login_required()
def give_feedback(request):
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            actual_user = request.user
            actual_user_message = form.cleaned_data['message']
            context = {
                'actual_user': actual_user,
                'actual_user_message': actual_user_message,
            }
            send_feedback_email(request, context)
            messages.success(request, 'Письмо отправлено!')
            return redirect('home')

        messages.warning(request, 'Ошибка отправки')
        return redirect('feedback')

    form = FeedbackForm()
    return render(request, 'news/feedback.html', {'form': form})

news/templates/news/add_post.html
{% extends "base_news.html" %}
{% load crispy_forms_tags %}

{% block title%} Добавить новость {%endblock%}

{% block headline %} Добавить новость {% endblock %}

{% block content %}

<div class="container">
  <div class="row justify-content-center">
    <div class="col-4">
      <form action="{% url 'add_post' %}" method="post" enctype="multipart/form-data" >

        {% csrf_token %}
        {{ form.media }}
        {{ form|crispy }}

        <button type="submit" class="btn btn-primary btn-lg btn-block" value="Submit"> Добавить новость </button>

      </form>
    </div>
  </div>
</div>
{% endblock %}

news/templates/news/author_full_list.html
{% extends "base_news.html" %}
{% load crispy_forms_tags %}
{% load news_extras %}

{% block title%} Авторы блога  {%endblock%}

{% block headline %} Авторы блога {% endblock %}


{% load static %}
{% load news_extras %}

{% block content %}

{% author_full_list %}

{% endblock %}

news/templates/news/author_full_list_teg.html
<div class="container">
  <div class="row">
    {% for authors in authors %}
    <div class="card" style="width: 25rem;">
      {% if authors.photo %}
      <img width="200px" height="249px" src="{{ authors.photo.url }}" class="card-img-top" alt="...">
      {% else %}
      <img src="https://dummyimage.com/600x400/000/1320d4.png&text=Заглушка  " class="card-img-top" alt="...">

      {% endif%}
      <div class="card-body">
        <h5 class="card-title"> Имя:{{ authors.full_name }} </h5>
        <p class="card-text"> О себе: {{ authors.profileauthor.bio|truncatechars:50|safe }}</p>
        <p class="card-text"><small class="text-muted">Любимая категория: {{ authors.profileauthor.category }} </small></p>
        <p class="card-text"> Постов - {{ authors.number}}</p>

        <a href="{{ authors.get_profile_url }}" class="btn btn-primary">Полный профиль</a>

      </div>
    </div>
    {% endfor %}
  </div>
</div>

news/templates/news/author_news_list.html
{% extends "base_news.html" %}

{% block title%} Новостной блоге {%endblock%}

{% block headline %} Автор: {{ name_author }} {% endblock %}

{% block content %}

<div class="container">
  <div class="row">
    
{% for post in page_obj %}
    <div class="card" style="width: 25rem;">
      {% if post.preview_photo %}
        <img width="200px" height="249px" src="{{ post.preview_photo.url }}" class="card-img-top" alt="...">
      {% else %}
        <img src="https://dummyimage.com/600x400/000/1320d4.png&text=Заглушка  " class="card-img-top" alt="...">

      {% endif%}
      <div class="card-body">
        <h6 class="card-subtitle mb-2 text-muted">Категория: {{ post.category }}</h6>
        <h5 class="card-title">{{post.title}}</h5>
        <p class="card-text">{{ post.content|truncatechars:50|safe }}</p>
         <p class="card-text"><small class="text-muted">Последние изменения: {{post.date_change}}</small></p>
         <p class="card-text"><small class="text-muted">Автор: {{post.author}}</small></p>
        <a href="{{ post.get_absolute_url }}" class="btn btn-primary">Читать далее</a>
      </div>
    </div>
{% endfor %}
  </div>
</div>

{% endblock %}

news/templates/news/category_news_list.html
{% extends "base_news.html" %}

{% block title%} Новостной блоге {%endblock%}

{% block headline %} Категория: {{ selected_category.title }} {% endblock %}

{% block content %}

<div class="container">
  <div class="row">
{% for post in page_obj %}
    <div class="card" style="width: 25rem;">
      {% if post.preview_photo %}
        <img width="200px" height="249px" src="{{ post.preview_photo.url }}" class="card-img-top" alt="...">
      {% else %}
        <img src="https://dummyimage.com/600x400/000/1320d4.png&text=Заглушка  " class="card-img-top" alt="...">

      {% endif%}
      <div class="card-body">
        <h6 class="card-subtitle mb-2 text-muted">Категория: {{ post.category }}</h6>
        <h5 class="card-title">{{post.title}}</h5>
        <p class="card-text">{{ post.content|truncatechars:50|safe }}</p>
         <p class="card-text"><small class="text-muted">Последние изменения: {{post.date_change}}</small></p>
         <p class="card-text"><small class="text-muted">Автор: <a href="{{ post.author.get_absolute_url }}">{{post.author}}</a></small></p>
        <a href="{{ post.get_absolute_url }}" class="btn btn-primary">Читать далее</a>
      </div>
    </div>
{% endfor %}
  </div>
</div>

{% endblock %}

news/templates/news/feedback.html
{% extends "base_news.html" %}
{% load crispy_forms_tags %}

{% block content %}



<div class="container">
  <div class="row justify-content-center">
    <div class="col-4">
      <form action="{% url 'feedback' %}" method="post">
        {% csrf_token %}
        {{ form|crispy }}

        <button type="submit" class="btn btn-primary btn-lg btn-block" value="Submit">Отправить письмо</button>

      </form>
    </div>
  </div>
</div>
{% endblock %}

news/templates/news/feedback_email.html
{% autoescape off %}

Письмо с сайта от пользователя {{ actual_user.full_name}}
email пользователя: {{ actual_user.email }}

Сообщение:
{{ actual_user_message }}



{% endautoescape %}

news/templates/news/full_news.html
{% extends "base.html" %}

<style>
  @media screen and (min-width: 600px) {
    .children form {
      margin-left: -48px;
      /* will touch very left side */
    }

    .children .children form {
      margin-left: -96px;
      /* will touch very left side */
    }
  }
</style>


{% load crispy_forms_tags %}


{% block title%} Новостной блоге {%endblock%}

{% block headline %} {{ selected_post.title }} {% endblock %}



{% block content %}

<div class="container">
  <div class="row">

    <div class="card" style="width: 100%;">
      {% if selected_post.preview_photo %}
      <img width="200px" height="249px" src="{{ selected_post.preview_photo.url }}" class="card-img-top" alt="...">
      {% else %}
      <img src="https://dummyimage.com/300x100/000/1320d4.png&text=Заглушка  " class="card-img-top" alt="...">

      {% endif%}
      <div class="card-body">
        <h6 class="card-subtitle mb-2 text-muted">Категория:<a href="{{ selected_post.category.get_absolute_url }}">{{ selected_post.category }}</a></h6>
        <h5 class="card-title">{{selected_post.title}}</h5>
        <p class="card-text">{{ selected_post.content|safe }}</p>
        <p class="card-text"><small class="text-muted">Последние изменения: {{selected_post.date_change}}</small></p>
        <p class="card-text"><small class="text-muted">Автор: <a href="{{ selected_post.author.get_absolute_url }}">{{selected_post.author}}</a></small></p>
        <a href="{% url 'home' %}" class="btn btn-primary">На главную</a>
        {% if user == selected_post.author %}
        <a href="{{ selected_post.get_update_url }}" class="btn btn-primary">Редактировать запись</a>
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
          <a href="{{selected_post.get_delete_url }}" type="button" class="btn btn-outline-danger">Удалить запись?</a>
        </div>
        {% endif %}
      </div>
    </div>

  </div>
</div>

{% endblock %}

{% block comments %}
<div class="container">
  <div class="row justify-content-center">

    <div class="col-4">
      <form action="{{selected_post.get_absolute_url}}" method="post">

        {% csrf_token %}
        {{ form.comment_text|as_crispy_field }}


        <button type="submit" class="btn btn-primary btn-lg btn-block" value="Submit">Оставить комментарий</button>

      </form>
    </div>
  </div>
</div>

<div class="container">
  <div class="row justify-content-md-center pt-5">

    <div class="col-md-12">

      {% load mptt_tags %}
      <div>
        {% recursetree comments %}

        <div class="ms-2 p-4" style="border: 1px solid grey">
          <div class="d-flex justify-content-between">Пользователь: {{ node.user }}
            <div></div>{{ node.publication_date }}
          </div>

          <div id="{{ node.id }}">{{ node.comment_text }}</div>
          <hr />

          {% if node.level < 3 %}
          <button class="button" onclick="myFunction({{ node.id }})">Ответить</button>
          {% endif %}
        </div>

        {% if not node.is_leaf_node %}
        <div class="children pl-3 ms-5">

          <div class="d-flex justify-content-between">Ответ пользователю: {{ node.user }} </div>

          {{ children }}
        </div>
        {% endif %}
        {% endrecursetree %}
      </div>
    </div>

    <script>
      function formExit() {
        document.getElementById("newForm").remove();
      }

      function myFunction(id) {
        if (document.contains(document.getElementById("newForm"))) {
          document.getElementById("newForm").remove();
        }

        var d1 = document.getElementById(id);
        d1.insertAdjacentHTML('afterend',
        '<form id="newForm" class="form-insert py-2" method="post"> \
             <div class="d-flex justify-content-between"><h2>Ваш комментарий:</h2><div><button type="button" class="btn btn-outline-secondary" onclick="formExit()"">Закрыть</button></div></div> \
             <select name="parent" class="d-none" id="id_parent"> \
             <option value="' + id + '" selected="' + id + '"></option> \
             </select> \
             <textarea name="comment_text" cols="40" rows="5" class="form-control" required id="id_comment_text"></textarea> \
             {% csrf_token %} \
             <button type="submit" class="btn btn-primary btn-lg btn-block">Ответить</button> \
           </form>');

          document.querySelector('#id_parentt [value="' + id + '"]').selected = true;
        }

        $('#myForm').trigger("reset");
    </script>
    
    {% endblock %}

news/templates/news/list_author.html
{% for author in number_author_category %}
  <li><a href="{{ author.get_absolute_url }}"> {{ author.full_name }} - <span class="badge bg-info text-dark"> {{ author.number }} </span></a></li>
{% endfor %}

news/templates/news/list_category.html
{% load mptt_tags %}

<div class="iocn-link">
  <a href="#">
    <i class='bx bx-collection' ></i>
    <span class="link_name">Категории </span>
  </a>
  <i class='bx bxs-chevron-down arrow' ></i>
</div>
<ul class="sub-menu">
  <li><a class="link_name" href="#">Категории</a></li>

  {% recursetree number_posts_category %}
    <li>
      <a href="{{ node.get_absolute_url }}">
      {{ node.title }} -
        {{node.number}}
      {% if not node.is_leaf_node %}
          <ul class="children">
              {{ children }}
          </ul>
      {% endif %}
    </a>
  </li>
  {% endrecursetree %}
</ul>

news/templates/news/post_delete.html
{% extends "base_news.html" %}
{% load crispy_forms_tags %}

{% block title%} Удаление {%endblock%}

{% block headline %} Удалить новость {% endblock %}

{% block content %}

<div class="container">
<div class="row">
  <div class="card" style="width: 100%;">
    <div class="card-body">
      <form action="{{ post.get_delete_url }}" method="post">
        {% csrf_token %}
        <h5 class="card-title text-center">Вы уверены что хотите удалть новость "{{ post.title }}" ?</h5> <br>
        <div class="d-grid gap-2 col-6 mx-auto">
          <a href="{{ post.get_absolute_url }}" class="btn btn-primary" type="button">Вернуться назад</a>
          <button  class="btn btn-outline-danger" type="submit">Удалить</button>
        </div>
      </form>
    </div>
  </div>
</div>

</div>



{% endblock%}

news/templates/news/post_update.html
{% extends "base_news.html" %}
{% load crispy_forms_tags %}

{% block title%} Изменить новость {%endblock%}

{% block headline %} Изменить новость {% endblock %}

{% block content %}



<div class="container">
  <div class="row justify-content-center">
    <div class="col-4">
      <form action="{{ post.get_update_url }}" method="post" enctype="multipart/form-data" >

        {% csrf_token %}
        {{ form.media }}
        {{ form|crispy }}

        <button type="submit" class="btn btn-primary btn-lg btn-block" value="Submit"> Добавить новость </button>

      </form>
    </div>
  </div>
</div>


{% endblock %}

news/templates/news/unauthorized_user.html
{% extends "base_news.html" %}
{% load news_extras %}



{% block about_site %}

<div class="container">
  <div class="row">
    <div class="col">
      <p class="fs-2 text-warning"> После прохождения регистрации вы сможете просматривать посты авторов нашего
        блога. Изучить авторов вы можете ниже. Если вы уже зарегистрированы, пожалуйста, авторизуйтесь. Если у вас нет аккаунта пройдите
        процедуру регистрации.</p>

      <a href="{% url 'registration' %}" type="button" class="btn btn-outline-primary">Регистрация</a>
      <a href="{% url 'authorization' %}" type="button" class="btn btn-outline-secondary">Вход</a>


    </div>
  </div>
</div>
<br>
{% author_full_list %}
{% endblock %}